[tool.black]
line-length = 99

[tool.isort]
line_length = 99
profile = "black"
multi_line_output = 3
lines_after_imports = 2
default_section = "THIRDPARTY"
known_first_party = "terraform_client,tests"
sections = "STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
