---
# https://circleci.com/docs/2.1/language-python/
version: 2.1


filters: &release-filters
  filters:
    tags:
      only: /[0-9]+(\.[0-9]+)*(-alpha\.[0-9]+)?/
    branches:
      ignore: /.*/

# ------------------
# Reusable executors
# ------------------

executors:

  standard:
    docker:
      - image: cimg/python:3.11.4
        environment:
          POETRY_VIRTUALENVS_IN_PROJECT: true
    working_directory: "~/lib"


# -----------------
# Reusable commands
# -----------------

commands:

  install_venv:
    steps:
      - restore_cache:
          keys:
            - virtualenv-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "poetry.lock" }}
            - virtualenv-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-
            - virtualenv-{{ .Environment.CACHE_VERSION }}-
      - run:
          name: Install Python packages
          command: make install
      - save_cache:
          key: virtualenv-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - "./.venv"


# --------------
# Pipeline tasks
# --------------

jobs:

  lint_package:
    executor: standard
    steps:
      - checkout
      - install_venv
      - run:
          name: Run Python linter
          command: make lint

  test_package:
    executor: standard
    steps:
      - checkout
      - install_venv
      - run:
          name: Run Python tests
          command: make test
      - store_test_results:
          path: "."

  build_wheel:
    executor: standard
    steps:
      - checkout
      - install_venv
      - run:
          name: Build wheel
          command: make package
      - store_artifacts:
          path: dist
          destination: wheel

  publish_wheel:
    executor: standard
    steps:
      - checkout
      - install_venv
      - run:
          name: Publish wheel
          command: make release


# -----------------
# Pipeline workflow
# -----------------

workflows:

  version: 2

  lint_test_build:
    jobs:
      - lint_package
      - test_package
      - build_wheel:
          requires:
            - lint_package
            - test_package

  publish:
    jobs:
      - approve_for_publishing:
          type: approval
          <<: *release-filters
      - publish_wheel:
          context: PYPI_SHARED
          requires:
            - approve_for_publishing
          <<: *release-filters
