# https://circleci.com/docs/2.1/language-python/
version: 2.1

# ------------------
# Reusable executors
# ------------------

executors:

  standard:
    docker:
      - image: cimg/python:3.8.6
        environment:
          POETRY_VIRTUALENVS_IN_PROJECT: true
    working_directory: "~/lib"


# -----------------
# Reusable commands
# -----------------

commands:

  install-venv:
    steps:
      - restore_cache:
          keys:
            - virtualenv-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "poetry.lock" }}
            - virtualenv-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-
            - virtualenv-{{ .Environment.CACHE_VERSION }}-
      - run:
          name: Install Python packages
          command: make install
      - save_cache:
          key: virtualenv-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - "./.venv"


# --------------
# Pipeline tasks
# --------------

jobs:

  lint-package:
    executor: standard
    steps:
      - checkout
      - install-venv
      - run:
          name: Run Python linter
          command: make lint

  test-package:
    executor: standard
    steps:
      - checkout
      - install-venv
      - run:
          name: Run Python tests
          command: make test
      - store_test_results:
          path: "."

  build-wheel:
    executor: standard
    steps:
      - checkout
      - install-venv
      - run:
          name: Build wheel
          command: make package
      - store_artifacts:
          path: dist
          destination: wheel

  publish-wheel:
    executor: standard
    steps:
      - checkout
      - install-venv
      - run:
          name: Publish wheel
          command: make release


# -----------------
# Pipeline workflow
# -----------------

workflows:

  version: 2

  lint-test-build:
    jobs:
      - lint-package
      - test-package
      - build-wheel:
          requires:
            - lint-package
            - test-package

  publish:
    jobs:
      - approve-for-publishing:
          type: approval
          filters:
            tags:
              # ONLY git tag compliant format: e.g. `0.0.1-alpha.01`
              only: /[0-9]+(\.[0-9]+)*(-alpha\.[0-9]+)?/
            branches:
              ignore: /.*/
      - publish-wheel:
          context: CIRCLECI_PYPI_SHARED
          requires:
            - approve-for-publishing
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*(-alpha\.[0-9]+)?/
            branches:
              ignore: /.*/
